name: CI
on:
  push:
    branches:
      - main
  pull_request:

defaults:
  run:
    shell: bash -xe {0}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: false
      - uses: golangci/golangci-lint-action@v6
      - run: make
  docker-build:
    uses: ./.github/workflows/docker-build.yml
    permissions:
      packages: write
    with:
      push: ${{ github.event_name == 'push' }}
      version: ${{ github.sha }}
